### ISSUE TITLE
Библиотека verbs.xml / возможные библиотеки

### ISSUE THREAD

**Issue by Wol4ik** [IFML2/ifml2#17]
в теле файла есть строчка вначале ```<library xmlns="http://toysoft.narod.ru/IFML2Schema" name="Глаголы">``` ссылка битая (404), предлагаю заменить или убрать.

Если существует утилита, при помощи которой конструировалась библиотека verbs.xml, было бы неплохо опубликовать ее название или ссылку. Создание своих библиотек расширяет спектр возможных игровых миров, где логика и набор возможных глаголов могут быть иными.

**Comment by realsonic** [comment]
@Wol4ik, библиотека правилась руками. Планировалась, чтобы можно было править библиотеки в Редакторе.
Эта ссылка не битая, это xml-неймспейс, он может ничего не возвращать. Но желательно, чтобы открывалась XSD-схема, по которой создаётся файл.

**Comment by realsonic** [comment]
@Wol4ik, закрываю issue?

**Comment by Wol4ik** [comment]
да, это ишью можно закрываать
